modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="copper_mod"
version="1.0.2"
displayName="Copper Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/BullfrogMods/minecraft-copper-mod"
authors="Jeremiah, MCreator"
description='''
Make copper useful! With this mod, armor and tools can be made from copper.
'''

[[dependencies.copper_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




