modLoader="javafml"
loaderVersion="[37,)"
license="Academic Free License v3.0"

[[mods]]
modId="copper_mod"
version="1.0.0"
displayName="Copper Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/BullfrogMods/minecraft-copper-mod"
authors="Jeremiah, MCreator"

[[dependencies.copper_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




